name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t balagouninaveen/backend:latest ./backend

      - name: Build frontend image
        run: docker build -t balagouninaveen/frontend:latest ./frontend

      - name: Push backend image
        run: docker push balagouninaveen/backend:latest

      - name: Push frontend image
        run: docker push balagouninaveen/frontend:latest
